# st.set_page_config(page_title="メインページ", page_icon='icon.png') #show icon
# st.title("Multiple OSS Access Log Analyzer")

import streamlit as st
import pandas as pd

uploaded_file = st.file_uploader(
    "Upload your food log",
    type=["xlsx", "xlsm"]
)

# check the contents in the excel file 
if uploaded_file is not None:

    df = pd.read_excel(
        uploaded_file,
        header=None
    )

    st.write(df.head(20))

# main 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "151ff095-9aa8-4972-a47d-a9c55604d01d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "03063bde-ec4b-4385-8b9e-2e9902004ab1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[\n",
      "  {\n",
      "    \"source\": \"Report_038.xlsm\",\n",
      "    \"output_html\": \"Report_038_ai_production_batch_final.html\",\n",
      "    \"period\": \"14.05.26 - 14.06.26\",\n",
      "    \"header_row\": 3,\n",
      "    \"column_map\": {\n",
      "      \"calories\": 3,\n",
      "      \"fat_g\": 4,\n",
      "      \"carbs_g\": 5,\n",
      "      \"protein_g\": 6,\n",
      "      \"sat_fat_g\": 7,\n",
      "      \"trans_fat_g\": 8,\n",
      "      \"fiber_g\": 9,\n",
      "      \"sodium_mg\": 10,\n",
      "      \"calcium_mg\": 11\n",
      "    },\n",
      "    \"score\": 57,\n",
      "    \"actions\": [\n",
      "      \"PFC balance: Your protein, fat, and carbohydrate balance is fairly close to a good pattern.\",\n",
      "      \"Add more for total fat: 🥑 Avocado (1/2 fruit per meal)\",\n",
      "      \"Add more for carbohydrates: 🍚 Rice (1 bowl per meal)\",\n",
      "      \"Reduce for sodium: 🍜 Soup/instant noodles: reduce 1 bowl/pack per day\",\n",
      "      \"Meal logging: breakfast, dinner was recorded less often. Recording it more regularly will make the report more accurate.\"\n",
      "    ],\n",
      "    \"sweet_count\": 10,\n",
      "    \"alcohol_count\": 2,\n",
      "    \"add_preview\": [\n",
      "      {\n",
      "        \"Nutrient\": \"🥑Total Fat\",\n",
      "        \"🔴 Current Gap\": \"-34 g (51%)\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🥩 Slow smoked bbq beef brisket by Smokey bones bar &amp; grill: 38 g\",\n",
      "        \"Suggested food\": \"🥑 Avocado (1/2 fruit per meal)\"\n",
      "      },\n",
      "      {\n",
      "        \"Nutrient\": \"\",\n",
      "        \"🔴 Current Gap\": \"\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🥩 Grilled pork: 26 g\",\n",
      "        \"Suggested food\": \"🥜 Mixed nuts (30g per day)\"\n",
      "      },\n",
      "      {\n",
      "        \"Nutrient\": \"\",\n",
      "        \"🔴 Current Gap\": \"\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🍚 Rice noodle bowl with pork and spring rolls: 24 g\",\n",
      "        \"Suggested food\": \"🫒 Olive oil (1 tbsp per meal)\"\n",
      "      },\n",
      "      {\n",
      "        \"Nutrient\": \"🍙Carbohydrates\",\n",
      "        \"🔴 Current Gap\": \"-41 g (84%)\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🍜 Japanese style ramen noodles by simply asia: 225 g\",\n",
      "        \"Suggested food\": \"🍚 Rice (1 bowl per meal)\"\n",
      "      }\n",
      "    ],\n",
      "    \"reduce_preview\": [\n",
      "      {\n",
      "        \"Nutrient\": \"🧂Sodium\",\n",
      "        \"🔴 Current Excess\": \"+3648 mg (259%)\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🥗 Vegetable soup: 41288 mg\",\n",
      "        \"Suggested food\": \"🍜 Soup/instant noodles: reduce 1 bowl/pack per day\"\n",
      "      },\n",
      "      {\n",
      "        \"Nutrient\": \"\",\n",
      "        \"🔴 Current Excess\": \"\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🥩 Pork flavor &amp; mushroom soup mix by pamana: 20571 mg\",\n",
      "        \"Suggested food\": \"🧂 Soy sauce/fish sauce: use half the usual amount\"\n",
      "      },\n",
      "      {\n",
      "        \"Nutrient\": \"\",\n",
      "        \"🔴 Current Excess\": \"\",\n",
      "        \"📊 Your Top 3 Food (from data)\": \"🍚 Jok fat free chicken instant rice porridge by pum: 3058 mg\",\n",
      "        \"Suggested food\": \"🥒 Pickled/processed foods: reduce 1 serving per day\"\n",
      "      }\n",
      "    ]\n",
      "  }\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "from pathlib import Path\n",
    "import re, json, math, html, base64, io\n",
    "from collections import Counter\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from openpyxl import load_workbook\n",
    "\n",
    "DEFAULT_BASE = Path.cwd()\n",
    "FALLBACK_BASE = Path('/mnt/data')\n",
    "\n",
    "def resolve_base(base_dir=None):\n",
    "    if base_dir is not None:\n",
    "        return Path(base_dir)\n",
    "    cwd = Path.cwd()\n",
    "    if list(cwd.glob('Report_*.xlsm')):\n",
    "        return cwd\n",
    "    if list(FALLBACK_BASE.glob('Report_*.xlsm')):\n",
    "        return FALLBACK_BASE\n",
    "    return cwd\n",
    "\n",
    "ICONS = {\n",
    "    'book': '\\U0001F4D8', 'date': '\\U0001F4C5', 'trophy': '\\U0001F3C6', 'fire': '\\U0001F525',\n",
    "    'memo': '\\U0001F4DD', 'pie': '\\U0001F967', 'chart': '\\U0001F4C8', 'target': '\\U0001F3AF',\n",
    "    'lab': '\\U0001F9EA', 'sweet': '\\U0001F9CB', 'alcohol': '\\U0001F377', 'calories': '\\U0001F525',\n",
    "    'fat': '\\U0001F951', 'carbs': '\\U0001F359', 'protein': '\\U0001F356', 'satfat': '\\U0001F9C8',\n",
    "    'transfat': '\\U0001F35F', 'fiber': '\\U0001F966', 'sodium': '\\U0001F9C2', 'calcium': '\\U0001F9B4',\n",
    "    'ok': '\\u2705'\n",
    "}\n",
    "\n",
    "DAY_RE = re.compile(r'^[A-Za-z]+,\\s+[A-Za-z]+\\s+\\d{1,2}$')\n",
    "MEALS = {'Breakfast', 'Lunch', 'Dinner', 'Snacks'}\n",
    "ADEQUACY = {'Total Fat', 'Carbohydrates', 'Protein', 'Saturated Fat', 'Fiber', 'Calcium'}\n",
    "MODERATION = {'Trans Fat', 'Sodium'}\n",
    "DISPLAY = {\n",
    "    'calories': 'Calories', 'fat_g': 'Total Fat', 'carbs_g': 'Carbohydrates', 'protein_g': 'Protein',\n",
    "    'sat_fat_g': 'Saturated Fat', 'trans_fat_g': 'Trans Fat', 'fiber_g': 'Fiber', 'sodium_mg': 'Sodium',\n",
    "    'calcium_mg': 'Calcium'\n",
    "}\n",
    "NUTRIENT_ORDER = ['fat_g', 'carbs_g', 'protein_g', 'sat_fat_g', 'trans_fat_g', 'fiber_g', 'sodium_mg', 'calcium_mg']\n",
    "TARGET_ALIASES = {\n",
    "    'calories': ['calories'], 'fat_g': ['total fat'], 'carbs_g': ['total carbs', 'carbs', 'carbohydrates'],\n",
    "    'protein_g': ['protein'], 'sat_fat_g': ['sat fat', 'saturated fat'], 'trans_fat_g': ['trans fat'],\n",
    "    'fiber_g': ['fiber'], 'sodium_mg': ['sodium'], 'calcium_mg': ['calcium']\n",
    "}\n",
    "TARGET_DEFAULTS = {'calories': 2000.0, 'fat_g': 70.0, 'carbs_g': 250.0, 'protein_g': 90.0, 'sat_fat_g': 20.0, 'trans_fat_g': 0.0, 'fiber_g': 20.0, 'sodium_mg': 2300.0, 'calcium_mg': 1000.0}\n",
    "NUTRIENT_ICON_KEY = {'Calories': 'calories', 'Total Fat': 'fat', 'Carbohydrates': 'carbs', 'Protein': 'protein', 'Saturated Fat': 'satfat', 'Trans Fat': 'transfat', 'Fiber': 'fiber', 'Sodium': 'sodium', 'Calcium': 'calcium'}\n",
    "\n",
    "ADD_FOODS = {\n",
    "    'Calories': [\"\\U0001F35A Rice (1 bowl per meal)\", \"\\U0001F35E Bread (2 slices)\", \"\\U0001F34C Banana (1 piece)\"],\n",
    "    'Total Fat': [\"\\U0001F951 Avocado (1/2 fruit per meal)\", \"\\U0001F95C Mixed nuts (30g per day)\", \"\\U0001FAD2 Olive oil (1 tbsp per meal)\"],\n",
    "    'Carbohydrates': [\"\\U0001F35A Rice (1 bowl per meal)\", \"\\U0001F360 Sweet potato (100g per meal)\", \"\\U0001F35E Bread (2 slices)\"],\n",
    "    'Protein': [\"\\U0001F95A Egg (1 egg per meal)\", \"\\U0001F41F Chicken or fish (100g per meal)\", \"\\U0001F9CA Tofu or yogurt (150g tofu / 1 cup yogurt per day)\"],\n",
    "    'Saturated Fat': [\"\\U0001F95B Milk (1 cup per day)\", \"\\U0001F9C0 Cheese (30g per day)\", \"\\U0001F95A Egg (1 egg per meal)\"],\n",
    "    'Fiber': [\"\\U0001F966 Vegetables (1 cup per meal)\", \"\\U0001F34E Fruit (1 piece per day)\", \"\\U0001FAD8 Beans or lentils (1/2 cup per day)\"],\n",
    "    'Calcium': [\"\\U0001F95B Milk (1 cup per day)\", \"\\U0001F963 Yogurt (1 cup per day)\", \"\\U0001F9CA Tofu (150g per meal)\"]\n",
    "}\n",
    "REDUCE_FOODS = {\n",
    "    'Total Fat': [\"\\U0001F357 Fried foods: reduce 1 serving per day\", \"\\U0001F96B Creamy sauces: use less\", \"\\U0001F969 Fatty meat: choose lean meat instead\"],\n",
    "    'Carbohydrates': [\"\\U0001F35A Rice/noodles: reduce about 1/2 bowl per meal\", \"\\U0001F370 Sweets: reduce 1 serving per day\", \"\\U0001F9CB Sugary drinks: reduce 1 bottle/can per day\"],\n",
    "    'Protein': [\"\\U0001F969 Large meat portions: keep to about 100g per meal\", \"\\U0001F357 Avoid several big meat dishes in one day\", \"\\U0001F953 Limit processed meat like bacon or sausage\"],\n",
    "    'Saturated Fat': [\"\\U0001F9C8 Butter/cream: use less\", \"\\U0001F950 Pastries: reduce 1 serving per day\", \"\\U0001F357 Choose grilled dishes more often\"],\n",
    "    'Trans Fat': [\"\\U0001F35F Packaged fried snacks: reduce 1 serving per day\", \"\\U0001F950 Fast food/pastries: reduce 1 serving per day\", \"\\U0001F373 Choose simple cooked foods more often\"],\n",
    "    'Sodium': [\"\\U0001F35C Soup/instant noodles: reduce 1 bowl/pack per day\", \"\\U0001F9C2 Soy sauce/fish sauce: use half the usual amount\", \"\\U0001F952 Pickled/processed foods: reduce 1 serving per day\"]\n",
    "}\n",
    "SWEET_PATTERNS = ['bubble tea', 'milk tea', 'latte', 'cake', 'dessert', 'cookie', 'ice cream', 'coke', 'cola', 'soft drink', 'syrup', 'sweetened', 'iced coffee with milk', 'shaved ice dessert', 'fruit dessert', 'croissant', 'pastry']\n",
    "ALCOHOL_WORDS = ['wine', 'beer', 'cabernet', 'whisky', 'whiskey', 'vodka', 'rum', 'gin', 'tequila', 'sake', 'soju', 'cider']\n",
    "ALCOHOL_RE = re.compile(r'\\b(?:' + '|'.join(sorted(map(re.escape, ALCOHOL_WORDS), key=len, reverse=True)) + r')\\b', re.I)\n",
    "\n",
    "CSS = \"\"\"\n",
    "@page { size:A4; margin:10.5mm; }\n",
    "body { font-family:'Arial','Noto Color Emoji','Segoe UI Emoji','Apple Color Emoji',sans-serif; margin:0; color:#1f2937; background:#f5f7fb; font-size:10pt; line-height:1.22; }\n",
    "h1,h2,h3 { margin:0 0 5px 0; } h1 { font-size:22pt; color:#0f2b46; } h2 { font-size:12.4pt; color:#0f2b46; } h3 { font-size:10.6pt; color:#20486d; }\n",
    ".sub { color:#667085; margin-bottom:8px; font-size:9pt; }\n",
    ".grid { display:grid; grid-template-columns:repeat(3,1fr); gap:8px; margin-bottom:8px; }\n",
    ".card,.section { background:#fff; border:1px solid #d7dde7; border-radius:12px; padding:9px; box-shadow:0 1px 2px rgba(17,24,39,.05); break-inside:avoid; page-break-inside:avoid; }\n",
    ".metric { font-size:22px; font-weight:700; margin-top:4px; color:#0f2b46; }\n",
    ".two-col { display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-bottom:8px; }\n",
    ".stack { display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-bottom:8px; }\n",
    "ul { margin:6px 0 0 16px; padding-left:0; } li { margin-bottom:4px; }\n",
    "img { max-width:100%; border:1px solid #e8edf5; border-radius:8px; }\n",
    "table.data-table { width:100%; border-collapse:collapse; font-size:8.7pt; }\n",
    "table.data-table th, table.data-table td { padding:4px 5px; border-bottom:1px solid #edf2f7; text-align:left; vertical-align:top; }\n",
    "table.data-table th { background:#f8fafc; color:#334155; }\n",
    ".small { color:#667085; font-size:8pt; margin-bottom:4px; }\n",
    ".badge { display:inline-block; padding:2px 7px; border-radius:999px; font-weight:700; font-size:8pt; }\n",
    ".good { background:#E7F6EA; color:#2E7D32; } .warn { background:#FFF7E0; color:#A66A00; } .bad { background:#FDECEC; color:#C62828; }\n",
    ".callout { border-left:5px solid #2563eb; background:#eff6ff; padding:8px 10px; border-radius:9px; margin:7px 0 8px 0; font-size:8.8pt; }\n",
    ".ai-badge { display:inline-block; padding:2px 8px; border-radius:999px; background:#eef2ff; color:#3730a3; font-size:8pt; font-weight:700; }\n",
    "\"\"\"\n",
    "\n",
    "def strip_html(s):\n",
    "    s = '' if s is None else str(s)\n",
    "    s = re.sub(r'<[^>]+>', '', s)\n",
    "    return s.replace('&nbsp;', ' ').replace('\\xa0', ' ').strip()\n",
    "\n",
    "def clean(s): return re.sub(r'\\s+', ' ', strip_html(s)).strip()\n",
    "def normalize(s): return re.sub(r'[^a-z0-9]+', ' ', clean(s).lower()).strip()\n",
    "def esc(s): return html.escape(str(s))\n",
    "def n(v):\n",
    "    if v is None: return None\n",
    "    if isinstance(v, (int, float)): return float(v)\n",
    "    s = clean(v)\n",
    "    if not s or s in {'g', 'mg', 'cals'}: return None\n",
    "    m = re.search(r'[-+]?\\d[\\d,]*\\.?\\d*', s)\n",
    "    return float(m.group().replace(',', '')) if m else None\n",
    "\n",
    "def grade(v):\n",
    "    m = re.search(r'([ABCDF][+-]?)', clean(v))\n",
    "    return m.group(1) if m else clean(v)\n",
    "\n",
    "def unit_for(key): return 'mg' if key.endswith('_mg') else ('kcal' if key == 'calories' else 'g')\n",
    "def fmt(v, unit):\n",
    "    if v is None or (isinstance(v, float) and math.isnan(v)): return '-'\n",
    "    v = float(v)\n",
    "    return f'{v:.0f} {unit}' if unit in ('mg','kcal') or abs(v-round(v)) < 1e-9 else f'{v:.1f} {unit}'\n",
    "def nutrient_label(name): return ICONS[NUTRIENT_ICON_KEY[name]] + name\n",
    "\n",
    "def food_label(name):\n",
    "    raw = clean(name)\n",
    "    low = raw.lower()\n",
    "    rules = [\n",
    "        (['pizza'], '\\U0001F355'), (['rice porridge','porridge','congee','rice'], '\\U0001F35A'),\n",
    "        (['udon','spagehetti','spaghetti','noodle','rice noodle','pasta'], '\\U0001F35C'),\n",
    "        (['duck','pork','beef','steak','chicken','lamb','rib','patty','sirloin','salami'], '\\U0001F969'),\n",
    "        (['fish','shrimp','octopus','salmon','seafood'], '\\U0001F41F'), (['sandwich','bread','croissant','cracker'], '\\U0001F35E'),\n",
    "        (['milk','soy milk','yogurt','latte'], '\\U0001F95B'), (['cake','dessert','pudding','cookie','ice'], '\\U0001F37D'),\n",
    "        (['coffee','tea'], '\\u2615'), (['mango','orange','banana','watermelon','fruit','plum','papaya','melon','durian'], '\\U0001F34E'),\n",
    "        (['vegetable','spinach','cabbage','lettuce','cucumber','carrot','eggplant','greens','bean sprout'], '\\U0001F957'),\n",
    "        (['egg','omelette'], '\\U0001F95A'), (['tofu'], '\\U0001F9CA'), (['soup'], '\\U0001F372'), (['dumpling'], '\\U0001F95F')]\n",
    "    for needles, emo in rules:\n",
    "        if any(x in low for x in needles): return emo + ' ' + esc(raw)\n",
    "    if ALCOHOL_RE.search(low): return '\\U0001F377 ' + esc(raw)\n",
    "    return '\\U0001F37D ' + esc(raw)\n",
    "\n",
    "def open_rows(path):\n",
    "    wb = load_workbook(path, data_only=True, keep_vba=True)\n",
    "    ws = wb[wb.sheetnames[0]]\n",
    "    return [list(r) for r in ws.iter_rows(values_only=True)]\n",
    "\n",
    "def detect_header_row(rows):\n",
    "    for i, row in enumerate(rows[:30]):\n",
    "        cells = [normalize(c) for c in row if clean(c)]\n",
    "        score = sum([any(c == 'calories' for c in cells), any(c.startswith('total fat') for c in cells), any(c.startswith('carbs') or c.startswith('total carbs') or c.startswith('carbohydrates') for c in cells), any(c.startswith('protein') for c in cells), any('sodium' in c for c in cells), any('calcium' in c for c in cells)])\n",
    "        if score >= 5: return i\n",
    "    raise ValueError('Header row not found')\n",
    "\n",
    "def classify_header(cell):\n",
    "    t = normalize(cell)\n",
    "    if not t: return None\n",
    "    if 'fd grade' in t or t == 'grade': return 'food_grade'\n",
    "    if t == 'calories' or ' calories' in t: return 'calories'\n",
    "    if 'trans fat' in t: return 'trans_fat_g'\n",
    "    if 'sat fat' in t or 'saturated fat' in t: return 'sat_fat_g'\n",
    "    if 'total fat' in t: return 'fat_g'\n",
    "    if 'total carbs' in t or 'carbohydrate' in t or t.startswith('carbs'): return 'carbs_g'\n",
    "    if 'protein' in t: return 'protein_g'\n",
    "    if 'fiber' in t: return 'fiber_g'\n",
    "    if 'sodium' in t: return 'sodium_mg'\n",
    "    if 'calcium' in t: return 'calcium_mg'\n",
    "    return None\n",
    "\n",
    "def build_colmap(header_row):\n",
    "    out = {}\n",
    "    for idx, cell in enumerate(header_row):\n",
    "        key = classify_header(cell)\n",
    "        if key and key not in out: out[key] = idx\n",
    "    return out\n",
    "\n",
    "def parse_targets(rows, header_idx):\n",
    "    targets = {}\n",
    "    for i in range(min(12, len(rows))):\n",
    "        cells = [clean(x) for x in rows[i] if clean(x)]\n",
    "        if any(c.lower() == 'target' for c in cells):\n",
    "            for j in range(i+1, min(header_idx, i+10)):\n",
    "                vals = [clean(x) for x in rows[j] if clean(x)]\n",
    "                for cell in vals:\n",
    "                    m = re.match(r'^([\\d,]+(?:\\.\\d+)?)\\s*,\\s*(.+)$', cell)\n",
    "                    if m:\n",
    "                        num = float(m.group(1).replace(',', ''))\n",
    "                        label = normalize(m.group(2))\n",
    "                        for k, aliases in TARGET_ALIASES.items():\n",
    "                            if any(a in label for a in aliases): targets[k] = num\n",
    "            break\n",
    "    for k, v in TARGET_DEFAULTS.items(): targets.setdefault(k, v)\n",
    "    return targets\n",
    "\n",
    "def row_metrics(row, cmap):\n",
    "    d = {}\n",
    "    for k, idx in cmap.items():\n",
    "        val = row[idx] if idx < len(row) else None\n",
    "        d[k] = grade(val) if k == 'food_grade' else n(val)\n",
    "    return d\n",
    "\n",
    "def parse_period(rows):\n",
    "    title = clean(rows[0][0] if rows and rows[0] else '')\n",
    "    m = re.search(r'for\\s+([\\d./-]+)\\s+-\\s+([\\d./-]+)', title)\n",
    "    return f'{m.group(1)} - {m.group(2)}' if m else title\n",
    "\n",
    "def parse_workbook(path):\n",
    "    rows = open_rows(path)\n",
    "    header_idx = detect_header_row(rows)\n",
    "    cmap = build_colmap(rows[header_idx])\n",
    "    targets = parse_targets(rows, header_idx)\n",
    "    period = parse_period(rows)\n",
    "    avg_idx = None\n",
    "    for i in range(header_idx+1, min(header_idx+8, len(rows))):\n",
    "        if clean(rows[i][0] if rows[i] else '').startswith('Averages over the period'):\n",
    "            avg_idx = i\n",
    "            break\n",
    "    if avg_idx is None: avg_idx = header_idx + 1\n",
    "    avg = row_metrics(rows[avg_idx], cmap)\n",
    "    days, foods = [], []\n",
    "    current_day, current_meal = None, None\n",
    "    for i in range(avg_idx+1, len(rows)):\n",
    "        row = rows[i]; first = clean(row[0] if row else None)\n",
    "        if not first: continue\n",
    "        if DAY_RE.match(first):\n",
    "            current_day = first; current_meal = None; rec = row_metrics(row, cmap); rec['date'] = current_day; days.append(rec); continue\n",
    "        if first in MEALS: current_meal = first; continue\n",
    "        if first == 'Left': continue\n",
    "        if current_day:\n",
    "            rec = row_metrics(row, cmap)\n",
    "            if any(rec.get(k) is not None for k in ['calories','fat_g','carbs_g','protein_g','sat_fat_g','fiber_g','sodium_mg','calcium_mg']):\n",
    "                rec['date'] = current_day; rec['meal'] = current_meal or ''; rec['food_name'] = first; foods.append(rec)\n",
    "    return {'source': path.name, 'period': period, 'header_row': header_idx+1, 'column_map': cmap, 'targets': targets, 'avg': avg, 'days': pd.DataFrame(days), 'foods': pd.DataFrame(foods)}\n",
    "\n",
    "def classify_nutrients(avg, targets):\n",
    "    out = []\n",
    "    for key in NUTRIENT_ORDER:\n",
    "        intake, target = avg.get(key), targets.get(key)\n",
    "        if intake is None or target is None: continue\n",
    "        name = DISPLAY[key]; pct = 0.0 if not target else float(intake)/float(target)*100\n",
    "        if name in MODERATION:\n",
    "            if key == 'trans_fat_g' and target == 0:\n",
    "                status = 'Good' if float(intake) == 0 else 'Too much'; pct = 0.0 if float(intake) == 0 else 999.0\n",
    "            else: status = 'Too much' if pct > 120 else 'Good'\n",
    "        else:\n",
    "            if pct < 85: status = 'Not enough'\n",
    "            elif pct > 120: status = 'Too much'\n",
    "            else: status = 'Good'\n",
    "        out.append({'key': key, 'name': name, 'intake': float(intake), 'target': float(target), 'pct': pct, 'status': status, 'unit': unit_for(key)})\n",
    "    return out\n",
    "\n",
    "def overall_score(classified):\n",
    "    vals = []\n",
    "    for r in classified:\n",
    "        pct = r['pct']\n",
    "        if r['name'] in MODERATION: s = 10 if r['status'] == 'Good' else max(0, 10 - max(0, pct - 100) / 10)\n",
    "        else: s = max(0, min(100, pct) / 10) if pct <= 100 else max(0, 10 - (pct - 100) / 10)\n",
    "        vals.append(s)\n",
    "    return int(round(sum(vals)/len(vals)*10)) if vals else 0\n",
    "\n",
    "def pfc(avg):\n",
    "    p = (avg.get('protein_g') or 0) * 4; f = (avg.get('fat_g') or 0) * 9; c = (avg.get('carbs_g') or 0) * 4; total = p + f + c\n",
    "    return {'Protein': 0.0, 'Fat': 0.0, 'Carbohydrates': 0.0} if not total else {'Protein': round(p/total*100,1), 'Fat': round(f/total*100,1), 'Carbohydrates': round(c/total*100,1)}\n",
    "\n",
    "def top_foods(food_df, key, n_top=3):\n",
    "    if food_df.empty or key not in food_df.columns: return []\n",
    "    tmp = food_df[['food_name', key]].copy(); tmp[key] = pd.to_numeric(tmp[key], errors='coerce'); tmp = tmp.dropna(subset=[key]); tmp = tmp[tmp[key] > 0]; tmp = tmp.sort_values(key, ascending=False).drop_duplicates('food_name').head(n_top)\n",
    "    return tmp.to_dict('records')\n",
    "\n",
    "def build_add_reduce(classified, foods_df):\n",
    "    add_rows, reduce_rows = [], []\n",
    "    for r in classified:\n",
    "        name, key, unit = r['name'], r['key'], r['unit']\n",
    "        if name in ADEQUACY and r['status'] == 'Not enough':\n",
    "            gap = max(0, r['target'] - r['intake']); tops = top_foods(foods_df, key, 3); sugg = ADD_FOODS.get(name, ['-','-','-'])\n",
    "            for i in range(3):\n",
    "                top = f\"{food_label(tops[i]['food_name'])}: {fmt(tops[i][key], unit)}\" if i < len(tops) else ''\n",
    "                add_rows.append({'Nutrient': nutrient_label(name) if i == 0 else '', '\\U0001F534 Current Gap': f\"-{fmt(gap, unit)} ({r['pct']:.0f}%)\" if i == 0 else '', '\\U0001F4CA Your Top 3 Food (from data)': top, 'Suggested food': sugg[i] if i < len(sugg) else ''})\n",
    "        elif name in ADEQUACY and r['status'] == 'Too much':\n",
    "            excess = max(0, r['intake'] - r['target']); tops = top_foods(foods_df, key, 3); sugg = REDUCE_FOODS.get(name, ['-','-','-'])\n",
    "            for i in range(3):\n",
    "                top = f\"{food_label(tops[i]['food_name'])}: {fmt(tops[i][key], unit)}\" if i < len(tops) else ''\n",
    "                reduce_rows.append({'Nutrient': nutrient_label(name) if i == 0 else '', '\\U0001F534 Current Excess': f\"+{fmt(excess, unit)} ({r['pct']:.0f}%)\" if i == 0 else '', '\\U0001F4CA Your Top 3 Food (from data)': top, 'Suggested food': sugg[i] if i < len(sugg) else ''})\n",
    "        elif name in MODERATION and r['status'] == 'Too much':\n",
    "            excess = r['intake'] if key == 'trans_fat_g' and r['target'] == 0 else max(0, r['intake'] - r['target']); tops = top_foods(foods_df, key, 3); sugg = REDUCE_FOODS.get(name, ['-','-','-'])\n",
    "            for i in range(3):\n",
    "                top = f\"{food_label(tops[i]['food_name'])}: {fmt(tops[i][key], unit)}\" if i < len(tops) else ''\n",
    "                reduce_rows.append({'Nutrient': nutrient_label(name) if i == 0 else '', '\\U0001F534 Current Excess': f\"+{fmt(excess, unit)} ({r['pct']:.0f}%)\" if i == 0 else '', '\\U0001F4CA Your Top 3 Food (from data)': top, 'Suggested food': sugg[i] if i < len(sugg) else ''})\n",
    "    return pd.DataFrame(add_rows), pd.DataFrame(reduce_rows)\n",
    "\n",
    "def meal_logging(days_df, foods_df, total_days=30):\n",
    "    logged_days = int(days_df.shape[0]) if not days_df.empty else 0\n",
    "    meal_sets = {m: set(foods_df.loc[foods_df['meal'] == m, 'date']) if not foods_df.empty else set() for m in ['Breakfast','Lunch','Dinner']}\n",
    "    rates = {m: len(v)/total_days for m, v in meal_sets.items()}\n",
    "    df = pd.DataFrame([\n",
    "        {'Meal': 'Total logged days', 'Recorded days': logged_days, 'Out of 30 days': f'{logged_days}/30 ({logged_days/30*100:.1f}%)'},\n",
    "        {'Meal': 'Breakfast', 'Recorded days': len(meal_sets['Breakfast']), 'Out of 30 days': f\"{len(meal_sets['Breakfast'])}/30 ({rates['Breakfast']*100:.1f}%)\"},\n",
    "        {'Meal': 'Lunch', 'Recorded days': len(meal_sets['Lunch']), 'Out of 30 days': f\"{len(meal_sets['Lunch'])}/30 ({rates['Lunch']*100:.1f}%)\"},\n",
    "        {'Meal': 'Dinner', 'Recorded days': len(meal_sets['Dinner']), 'Out of 30 days': f\"{len(meal_sets['Dinner'])}/30 ({rates['Dinner']*100:.1f}%)\"},\n",
    "    ])\n",
    "    return rates, df\n",
    "\n",
    "def sweet_alcohol(foods_df):\n",
    "    if foods_df.empty: return 0, pd.DataFrame(columns=['Top 3 drinks/snacks','Count']), 0, pd.DataFrame(columns=['Top 3 alcohol drinks','Count'])\n",
    "    names = foods_df['food_name'].fillna('').map(clean)\n",
    "    sweet_mask = names.str.lower().apply(lambda s: any(p in s for p in SWEET_PATTERNS))\n",
    "    alc_mask = names.str.lower().apply(lambda s: bool(ALCOHOL_RE.search(s)))\n",
    "    sweet_df, alc_df = foods_df[sweet_mask].copy(), foods_df[alc_mask].copy()\n",
    "    sweet_count, alc_count = int(len(sweet_df)), int(len(alc_df))\n",
    "    sweet_freq = pd.DataFrame(Counter([food_label(x) for x in sweet_df['food_name']]).most_common(3), columns=['Top 3 drinks/snacks','Count']) if sweet_count else pd.DataFrame(columns=['Top 3 drinks/snacks','Count'])\n",
    "    alc_freq = pd.DataFrame(Counter([food_label(x) for x in alc_df['food_name']]).most_common(3), columns=['Top 3 alcohol drinks','Count']) if alc_count else pd.DataFrame(columns=['Top 3 alcohol drinks','Count'])\n",
    "    return sweet_count, sweet_freq, alc_count, alc_freq\n",
    "\n",
    "def daily_score(row, targets):\n",
    "    vals = []\n",
    "    for key in NUTRIENT_ORDER:\n",
    "        intake, target = row.get(key), targets.get(key)\n",
    "        if intake is None or pd.isna(intake) or target is None: continue\n",
    "        pct = 0 if target == 0 else float(intake)/float(target)*100\n",
    "        if DISPLAY[key] in MODERATION: s = 10 if pct <= 100 else max(0, 10 - (pct - 100) / 10)\n",
    "        else: s = max(0, min(pct, 100) / 10) if pct <= 100 else max(0, 10 - (pct - 100) / 10)\n",
    "        vals.append(s)\n",
    "    return round(sum(vals)/len(vals)*10, 1) if vals else None\n",
    "\n",
    "def best_worst(days_df, targets):\n",
    "    if days_df.empty: return pd.DataFrame(columns=['Section','Date','Score','Calories','Comment'])\n",
    "    x = days_df.copy(); x['daily_score'] = x.apply(lambda r: daily_score(r, targets), axis=1); x['calories_num'] = pd.to_numeric(x['calories'], errors='coerce'); x = x.dropna(subset=['daily_score'])\n",
    "    if x.empty: return pd.DataFrame(columns=['Section','Date','Score','Calories','Comment'])\n",
    "    best = x.sort_values(['daily_score','calories_num'], ascending=[False,True]).iloc[0]; worst = x.sort_values(['daily_score','calories_num'], ascending=[True,False]).iloc[0]\n",
    "    return pd.DataFrame([{'Section':'\\u2B50 The best nutrition day','Date':best['date'],'Score':f\"{float(best['daily_score']):.1f}\",'Calories':f\"{float(best['calories_num']):.0f} kcal\",'Comment':'Closer to the goal and more balanced overall.'},{'Section':'\\u26A0\\uFE0F The worst nutrition day','Date':worst['date'],'Score':f\"{float(worst['daily_score']):.1f}\",'Calories':f\"{float(worst['calories_num']):.0f} kcal\",'Comment':'Farther from the goal and less balanced overall.'}])\n",
    "\n",
    "def detailed_analysis(classified):\n",
    "    rows = []\n",
    "    for r in classified:\n",
    "        badge = '<span class=\"badge good\">good</span>' if r['status'] == 'Good' else ('<span class=\"badge warn\">not enough</span>' if r['status'] == 'Not enough' else '<span class=\"badge bad\">too much</span>')\n",
    "        rows.append({'Nutrient': nutrient_label(r['name']), 'Intake': fmt(r['intake'], r['unit']), 'Target': fmt(r['target'], r['unit']), '% of target': f\"{r['pct']:.0f}%\", 'Status': badge})\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "def local_actions(pfc_data, add_df, reduce_df, meal_rates, sweet_count, alcohol_count):\n",
    "    actions = []\n",
    "    p, f, c = pfc_data['Protein'], pfc_data['Fat'], pfc_data['Carbohydrates']\n",
    "    if 15 <= p <= 25 and 20 <= f <= 35 and 45 <= c <= 65: actions.append('PFC balance: Your protein, fat, and carbohydrate balance is fairly close to a good pattern.')\n",
    "    else:\n",
    "        if p < 15: actions.append('PFC balance: Protein looks low. Try adding eggs, fish, chicken, tofu, or yogurt.')\n",
    "        elif f > 35: actions.append('PFC balance: Fat looks high. Try using less fried food and creamy food.')\n",
    "        elif c > 65: actions.append('PFC balance: Carbohydrates look high. Try reducing part of rice, noodles, bread, or sweets.')\n",
    "        elif c < 45: actions.append('PFC balance: Carbohydrates look low. Try adding rice, bread, or sweet potato.')\n",
    "        else: actions.append('PFC balance: The overall balance is a little uneven.')\n",
    "    used = set()\n",
    "    if not add_df.empty:\n",
    "        for _, row in add_df.iterrows():\n",
    "            nutrient, suggest = row.get('Nutrient',''), row.get('Suggested food','')\n",
    "            if nutrient and suggest:\n",
    "                nutrient_name = re.sub(r'^[^A-Za-z]+', '', re.sub(r'<[^>]+>', '', str(nutrient))).strip().lower()\n",
    "                if nutrient_name not in used:\n",
    "                    actions.append(f'Add more for {nutrient_name}: {re.sub(r\"<[^>]+>\", \"\", suggest)}'); used.add(nutrient_name)\n",
    "                if len(used) >= 2: break\n",
    "    if not reduce_df.empty:\n",
    "        for _, row in reduce_df.iterrows():\n",
    "            nutrient, suggest = row.get('Nutrient',''), row.get('Suggested food','')\n",
    "            if nutrient and suggest:\n",
    "                nutrient_name = re.sub(r'^[^A-Za-z]+', '', re.sub(r'<[^>]+>', '', str(nutrient))).strip().lower()\n",
    "                actions.append(f'Reduce for {nutrient_name}: {re.sub(r\"<[^>]+>\", \"\", suggest)}'); break\n",
    "    low_meals = [m.lower() for m, r in meal_rates.items() if r < 0.6]\n",
    "    if low_meals: actions.append(f'Meal logging: {\", \".join(low_meals)} was recorded less often. Recording it more regularly will make the report more accurate.')\n",
    "    if sweet_count > 0: actions.append(f'Sweet drinks or sweets appeared {sweet_count} time(s). Reducing these first may help lower extra sugar and calories.')\n",
    "    if alcohol_count > 0: actions.append(f'Alcohol appeared {alcohol_count} time(s). Keeping alcohol occasional may help overall balance.')\n",
    "    return actions[:5]\n",
    "\n",
    "def plot_to_data_uri(draw_fn):\n",
    "    fig = plt.figure(figsize=(6,4), dpi=140); draw_fn(fig); buf = io.BytesIO(); plt.tight_layout(); plt.savefig(buf, format='png', dpi=140, bbox_inches='tight'); plt.close(fig)\n",
    "    return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')\n",
    "\n",
    "def pfc_uri(pfc_data):\n",
    "    def draw(fig):\n",
    "        ax = fig.add_subplot(111); vals = list(pfc_data.values())\n",
    "        if sum(vals) <= 0: ax.text(0.5,0.5,'No PFC data',ha='center',va='center'); ax.axis('off')\n",
    "        else: ax.pie(vals, labels=list(pfc_data.keys()), autopct='%1.1f%%', startangle=90)\n",
    "        ax.set_title('PFC Balance')\n",
    "    return plot_to_data_uri(draw)\n",
    "\n",
    "def daily_uri(days_df, target_cal):\n",
    "    def draw(fig):\n",
    "        ax = fig.add_subplot(111)\n",
    "        if not days_df.empty:\n",
    "            vals = pd.to_numeric(days_df['calories'], errors='coerce').fillna(0).tolist(); labels = [d.replace(',', '') for d in days_df['date'].astype(str).tolist()]\n",
    "            ax.bar(range(len(vals)), vals, color='#5b8bd8'); ax.plot(range(len(vals)), [target_cal]*len(vals), linestyle='--', color='#d9534f')\n",
    "            ax.set_xticks(range(len(vals))); ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=7); ax.set_ylabel('Calories'); ax.set_title('Daily calories')\n",
    "        else: ax.text(0.5,0.5,'No daily data',ha='center',va='center'); ax.axis('off')\n",
    "    return plot_to_data_uri(draw)\n",
    "\n",
    "def nutrient_uri(classified):\n",
    "    def draw(fig):\n",
    "        ax = fig.add_subplot(111); labels = [r['name'] for r in classified]; perc = [r['pct'] for r in classified]; colors = ['#4CAF50' if r['status']=='Good' else ('#F4B400' if r['status']=='Not enough' else '#DB4437') for r in classified]; clipped = [min(v,200) for v in perc]\n",
    "        ax.barh(range(len(labels)), clipped, color=colors); ax.axvline(100, linestyle='--', color='gray', linewidth=1); ax.set_xlim(0,220); ax.set_yticks(range(len(labels))); ax.set_yticklabels(labels); ax.set_xlabel('% of Target'); ax.set_title('Nutrient amount vs target')\n",
    "        for y, p in enumerate(perc): ax.text(min(p+2,202), y, f'{p:.0f}%', va='center', ha='left', fontsize=8)\n",
    "    return plot_to_data_uri(draw)\n",
    "\n",
    "def table_html(df): return '<p>No data</p>' if df is None or df.empty else df.to_html(index=False, border=0, classes='data-table', escape=False)\n",
    "\n",
    "def build_html(report):\n",
    "    classified = classify_nutrients(report['avg'], report['targets']); score = overall_score(classified); pfc_data = pfc(report['avg']); add_df, reduce_df = build_add_reduce(classified, report['foods']); meal_rates, meal_df = meal_logging(report['days'], report['foods']); sweet_count, sweet_df, alc_count, alc_df = sweet_alcohol(report['foods']); detail_df = detailed_analysis(classified); best_worst_df = best_worst(report['days'], report['targets']); actions = local_actions(pfc_data, add_df, reduce_df, meal_rates, sweet_count, alc_count)\n",
    "    action_items = ''.join(f'<li>{esc(x)}</li>' for x in actions) if actions else '<li>-</li>'\n",
    "    return f'''<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>Nutrition Analysis Report</title><style>{CSS}</style></head><body>\n",
    "    <h1>Nutrition Analysis Report</h1>\n",
    "    <div class=\"sub\">{ICONS['book']} <b>Source:</b> {esc(report['source'])} / {ICONS['date']} <b>Period:</b> {esc(report['period'])} / <span class=\"ai-badge\">AI comment mode: local-fallback</span></div>\n",
    "    <div class=\"grid\"><div class=\"card\"><div>{ICONS['trophy']} <b>Total nutrition score</b></div><div class=\"metric\">{score}</div></div><div class=\"card\"><div>{ICONS['fire']} <b>Average calories</b></div><div class=\"metric\">{int(round(report['avg'].get('calories') or 0))}</div><div>Target {int(round(report['targets'].get('calories') or 0))}</div></div><div class=\"card\"><div>{ICONS['memo']} <b>Variability</b></div><div class=\"metric\">{int(report['days'].shape[0])}/30</div><div>logged days / 30 days</div></div></div>\n",
    "    <div class=\"callout\"><b>ℹ\\uFE0F About Total nutrition score</b><br>This score is mimics The Healthy Eating Index (HEI) score, 🌟>80: Excellent! 👍 50-80: Good, but there's room for improvement. ⚠️< 50: Time to make some adjustments.  It shows how closely your eating habits match recommended guidelines for good health.</div>\n",
    "    <div class=\"two-col\"><div class=\"section\"><h2>{ICONS['pie']} PFC pie chart</h2><div class=\"small\">This shows how calories are split between protein, fat, and carbohydrates.</div><div class=\"small\">This section only explains the overall balance of protein, fat, and carbohydrate.</div><img src=\"{pfc_uri(pfc_data)}\"></div><div class=\"section\"><h2>{ICONS['ok']} Recommended actions</h2><div class=\"small\">Action points are generated only from PFC, add/reduce, meal logging, sweet drink frequency, and alcohol frequency.</div><ul>{action_items}</ul></div></div>\n",
    "    <div class=\"section\"><h2>{ICONS['date']} Meal recording over 30 days</h2><div class=\"small\">This shows how often each meal was recorded over 30 days.</div>{table_html(meal_df)}</div>\n",
    "    <div class=\"stack\"><div class=\"section\"><h2>{ICONS['chart']} Daily calories</h2><div class=\"small\">This shows daily calories compared with the goal.</div><img src=\"{daily_uri(report['days'], report['targets'].get('calories',0))}\"></div><div class=\"section\"><h2>{ICONS['target']} Nutrient amount vs target</h2><div class=\"small\">Green is okay, yellow is not enough, and red is too much. If a value is very high, the label still shows the full percentage.</div><img src=\"{nutrient_uri(classified)}\"></div></div>\n",
    "    <div class=\"two-col\"><div class=\"section\"><h2>{ICONS['lab']} Detailed nutrient analysis</h2><div class=\"small\">This table shows amount-based classification for nutrients.</div>{table_html(detail_df)}</div><div class=\"section\"><h2>\\u2B50 Best day / \\u26A0\\uFE0F Worst day</h2><div class=\"small\">These two days show the strongest and weakest overall balance.</div>{table_html(best_worst_df)}</div></div>\n",
    "    <div class=\"section\"><h2>\\u2795 Foods to add</h2><div class=\"small\">Only nutrients that are not enough are listed here.</div>{table_html(add_df)}</div>\n",
    "    <div class=\"section\"><h2>\\u2796 Foods to reduce</h2><div class=\"small\">Only nutrients that are too much are listed here.</div>{table_html(reduce_df)}</div>\n",
    "    <div class=\"two-col\"><div class=\"section\"><h2>{ICONS['sweet']} Sweet drink frequency</h2><p><b>Count:</b> {sweet_count} record(s)</p>{table_html(sweet_df)}</div><div class=\"section\"><h2>{ICONS['alcohol']} Alcohol frequency</h2><p><b>Count:</b> {alc_count} record(s)</p>{table_html(alc_df)}</div></div>\n",
    "    </body></html>''', {'score': score, 'actions': actions, 'sweet_count': sweet_count, 'alcohol_count': alc_count, 'add_preview': add_df.head(4).to_dict('records'), 'reduce_preview': reduce_df.head(4).to_dict('records')}\n",
    "\n",
    "def run_batch(input_files=None, base_dir=None):\n",
    "    base = resolve_base(base_dir)\n",
    "    files = [Path(p) for p in input_files] if input_files else sorted(base.glob('Report_*.xlsm'))\n",
    "    if not files:\n",
    "        raise FileNotFoundError(f'No Report_*.xlsm files found in {base}')\n",
    "    manifest_path = base / 'nutrition_report_production_batch_notebook_manifest.json'\n",
    "    manifest = []\n",
    "    for path in files:\n",
    "        if not path.is_absolute():\n",
    "            path = base / path\n",
    "        report = parse_workbook(path)\n",
    "        html_text, meta = build_html(report)\n",
    "        out = base / f'{path.stem}_ai_production_batch_final.html'\n",
    "        out.write_text(html_text, encoding='utf-8')\n",
    "        manifest.append({'source': report['source'], 'output_html': out.name, 'period': report['period'], 'header_row': report['header_row'], 'column_map': report['column_map'], **meta})\n",
    "    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')\n",
    "    print(json.dumps(manifest, ensure_ascii=False, indent=2))\n",
    "    return manifest\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    run_batch()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b907101-6ac3-40c9-8113-c02b7eb006d6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9536a7ba-d553-4d2d-9178-7f177b2a9426",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2025.12-py312",
   "language": "python",
   "name": "conda-env-anaconda-2025.12-py312-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
